### ISSUE TITLE
Deprecation Warning in Moodle 2.9

### ISSUE THREAD

**Issue by Kathrin84** [itamart/moodle-local_loginas#8]
Hi, 

as we've updated to Moodle 2.9, using your plugin throws a deprecation warning:
Deprecated local plugin navigation callback: Please rename 'local_loginas_extends_settings_navigation' to 'local_loginas_extend_settings_navigation'. Support for the old callback will be dropped in Moodle 3.1

This can be fixed by naming
function local_loginas_extend_settings_navigation(settings_navigation $settings, $context)
in local/loginas/lib.php on line 31.

Would you please fix this small issue?

We've encountered no further problems by using your plugin with Moodle 2.9 yet.

Thanks and kind regards,
Kathrin

**Comment by itamart** [comment]
Thanks for the note Kathrin. Version 2.9 of the plugin will be released by the end of August and the release will of course fix this issue. :-)

**Comment by enboig** [comment]
Your plugin is the last I miss to upgrade 2.9; any updates on the release date?

Thanks

**Comment by itamart** [comment]
Has just been released.
